### ISSUE TITLE
Issues with the `gatsby new` command

### ISSUE THREAD

**Issue by f0rr0** [kylegach/kylegach_com#2]
I am trying to use your blog as a starter template for mine using `gatsby new` but I guess you have modified the file structure.

**Comment by kylegach** [comment]
Sorry for the trouble you’re having, Siddharth.

I removed the required config.toml file from the repo, because it contains my Google Analytics tracking number. I’m still working out the best way to add the file back that doesn’t expose secrets like that. I would imagine this missing file is preventing `gatsby new` from working correctly.

In the meantime, clone the project and add a file called config.toml to the root directory, with these contents:

``` toml
siteTitle = "Site Title"
blogTitle = "Blog Title"
url = "http://example.com"
linkPrefix = "/example"
email = "name@example.com"
twitter = "@handle"
github = "username"

[js]
head = """
"""
analytics = """
"""
font = """
"""

favicons = '''
'''

[header]
text = '''
<p>Header text</p>
'''

[work]
title = "Work Title"
blurb = "Work blurb"
dir = "work"

[writing]
title = "Writing Title"
blurb = "Writing blurb"
dir = "writing"

[about]
title = "About Title"
text = '''
<p>About text</p>
'''
```

You should then be able to run `gatsby develop` and have things work as expected.
